name: Publish .NET Package to NuGet

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '9.0.x'
  GITHUB_USERNAME: 'SolarBAM404'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Pack with dotnet
      run: dotnet pack --configuration Release

    - name: Add NuGet Source
      run: dotnet nuget add source --username ${{ env.GITHUB_USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ env.GITHUB_USERNAME }}/index.json"

    - name: Publish to GitHub Packages - MongoDb-EntityFramework.Host
      run: dotnet nuget push "MongoDbEntityFramework.Host/bin/Release/MongoDbEntityFramework.Host.*.nupkg" --api-key "${{ secrets.PAT_GITHUB }}" --source "github" --skip-duplicate
